version: 2

jobs:
  build_and_test:
    environment:
      CC_TEST_REPORTER_ID: 45c013b6d2380a087f53ebc237a799b3ca09f1a3b05ddf96982637d42a9d6861
    machine:
      docker_layer_caching: true
    working_directory: ~/codeclimate/codeclimate-markdownlint
    steps:
      - checkout
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: make image
      - run: make citest
      - run: ./cc-test-reporter after-build -t simplecov --prefix="/usr/src/app"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_and_test